<?php
require_once __DIR__ . '/../config/db.php';
require_once __DIR__ . '/../lib/fpdf/fpdf.php'; // path to FPDF
require_once __DIR__ . '/../config/functions.php';

$id = intval($_GET['id'] ?? 0);
if (!$id) {
    die('Invalid quotation ID.');
}

/* ---------- FETCH QUOTATION ---------- */
$q = $mysqli->prepare("SELECT * FROM customers_quotations WHERE id = ?");
$q->bind_param("i", $id);
$q->execute();
$res = $q->get_result();
if ($res->num_rows === 0) {
    die('Quotation not found.');
}
$row = $res->fetch_assoc();

/* ---------- DECODE JSON FIELDS ---------- */
$jobs = json_decode($row['jobs_json'], true) ?? [];
$terms = json_decode($row['terms_json'], true) ?? [];

/* ---------- INITIALIZE PDF ---------- */
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetMargins(15, 15, 15);
$pdf->SetFont('Arial', 'B', 16);

/* ---------- HEADER ---------- */
$pdf->Cell(0, 10, 'Quotation', 0, 1, 'C');
$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 7, 'Ref No: ' . $row['ref_no'], 0, 1, 'R');
$pdf->Cell(0, 7, 'Date: ' . date('d M Y', strtotime($row['quotation_date'])), 0, 1, 'R');

$pdf->Ln(8);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'To:', 0, 1);
$pdf->SetFont('Arial', '', 11);
$pdf->MultiCell(0, 6, $row['attention'] ?? '');
$pdf->Ln(5);

/* ---------- SUBJECT & MESSAGE ---------- */
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'Subject:', 0, 1);
$pdf->SetFont('Arial', '', 11);
$pdf->MultiCell(0, 6, $row['subject'] ?? '');
$pdf->Ln(5);

$pdf->MultiCell(0, 6, $row['message'] ?? '');
$pdf->Ln(8);

/* ---------- JOB REQUIREMENTS ---------- */
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'Job Requirements', 0, 1);

if (count($jobs) > 0) {
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->SetFillColor(230, 230, 230);
    $pdf->Cell(10, 8, '#', 1, 0, 'C', true);
    $pdf->Cell(60, 8, 'Job Title', 1, 0, 'C', true);
    $pdf->Cell(40, 8, 'Employees', 1, 0, 'C', true);
    $pdf->Cell(40, 8, 'Rate (AED)', 1, 0, 'C', true);
    $pdf->Cell(40, 8, 'Start Date', 1, 1, 'C', true);

    $pdf->SetFont('Arial', '', 10);
    foreach ($jobs as $i => $j) {
        $pdf->Cell(10, 8, $i + 1, 1, 0, 'C');
        $pdf->Cell(60, 8, $j['job_title'] ?? '', 1);
        $pdf->Cell(40, 8, $j['num_employees'] ?? '', 1, 0, 'C');
        $pdf->Cell(40, 8, number_format($j['rate_pay'] ?? 0, 2), 1, 0, 'C');
        $pdf->Cell(40, 8, ($j['start_date'] ?? ''), 1, 1, 'C');
    }
} else {
    $pdf->SetFont('Arial', '', 10);
    $pdf->Cell(0, 8, 'No job requirements found.', 1, 1, 'C');
}
$pdf->Ln(10);

/* ---------- TERMS & CONDITIONS ---------- */
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'Terms & Conditions', 0, 1);
$pdf->SetFont('Arial', '', 10);

if (count($terms) > 0) {
    foreach ($terms as $i => $t) {
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->Cell(0, 6, ($i + 1) . '. ' . ($t['title'] ?? ''), 0, 1);
        $pdf->SetFont('Arial', '', 10);
        $pdf->MultiCell(0, 6, ($t['text'] ?? ''));
        $pdf->Ln(2);
    }
} else {
    $pdf->Cell(0, 6, 'No terms and conditions found.', 0, 1);
}
$pdf->Ln(8);

/* ---------- CLOSING ---------- */
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(0, 8, 'Closing Message', 0, 1);
$pdf->SetFont('Arial', '', 11);
$pdf->MultiCell(0, 6, $row['closing'] ?? '');

/* ---------- FOOTER ---------- */
$pdf->Ln(15);
$pdf->SetFont('Arial', 'I', 9);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(0, 8, 'Generated by JRJ CRM-ERP System on ' . date('d M Y H:i'), 0, 1, 'C');

/* ---------- OUTPUT ---------- */
$pdf->Output('I', "Quotation_{$row['ref_no']}.pdf"); // Display in browser
exit;
?>